name: rive_animated_icon
description: "This package provides rive animated icons that can be customized to suit your preference."
version: 2.0.0
repository: https://github.com/nikkieke/rive_animated_icons
issue_tracker: https://github.com/nikkieke/rive_animated_icons/issues
topics: [icons, animation]

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
